sudo: required
services:
  - docker

before_install:
  - docker build -t abhisheksr2407/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run abhisheksr2407/react-test npm test -- --coverage

after_success:
  - docker build -t abhisheksr2407/multi-client ./client
  - docker build -t abhisheksr2407/multi-nginx ./nginx
  - docker build -t abhisheksr2407/multi-server ./server
  - docker build -t abhisheksr2407/multi-worker ./worker

#Log in to the docker CLU
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#Take those images and push them to docker hub
- docker push abhisheksr2407/multi-client
- docker push abhisheksr2407/multi-nginx
- docker push abhisheksr2407/multi-server
- docker push abhisheksr2407/multi-worker

